-- MySQL Script generated by MySQL Workbench
-- Sun Jul  9 13:49:00 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Imagen
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Imagen
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Imagen` ;
USE `Imagen` ;

-- -----------------------------------------------------
-- Table `Imagen`.`tbimagen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Imagen`.`tbimagen` ;

CREATE TABLE IF NOT EXISTS `Imagen`.`tbimagen` (
  `Id` INT NOT NULL,
  `NombreImagen` VARCHAR(45) NULL,
  `imagen` LONGBLOB NULL,
  PRIMARY KEY (`Id`, `NombreImagen`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
